// Copyright 2019 Vaultex, Inc
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License a
//  
//    http://www.apache.org/licenses/LICENSE-2.
//    
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// +build ignore

// The make_version program is run by go generate to compile a version stamp
// to be compiled into the upspin binary.
// It does nothing unless $COMMIT_SHA is set, which is true only during
// the release process.
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"time"
)

func main() {
	log.SetPrefix("make_version")
	log.SetFlags(0)

	version := os.Getenv("COMMIT_SHA")
	if version == "" {
		return
	}

	output := fmt.Sprintf(outputFormat, time.Now().In(time.UTC).Format(time.UnixDate), version)

	err := ioutil.WriteFile("git_version.go", []byte(output), 0664)
	if err != nil {
		log.Fatal(err)
	}
}

const outputFormat = `
// Code generated by 'go run makeversion.go'. DO NOT EDIT.

package version

import (
	"fmt"
	"time"
)

func init() {
	var err error
	BuildTime, err = time.Parse(time.UnixDate, %[1]q)
	if err != nil {
		panic(err)
	}
	GitSHA = fmt.Sprintf("%%s", %[2]q)
}
`
